version: '3.4'

networks:
  frontend:
  backend:

services:
  eventshubcatalogapi:
    image: eventshub/catalogapi
    build:
      context: .\EventsHubCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=EventsHubDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      ExternalBaseUrl: http://localhost:7024
    ports:
      - "7024:80"
    container_name: eventshubcatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi123(!)
      SA_PASSWORD: ProductApi123(!)
    ports:
      - "1450:1433"
    container_name: eventshubsqlserver
    networks:
      - backend

  tokenserver:
    image: eventshub/tokenapi
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=tokensqlserver;Initial Catalog=TokenServiceDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      MvcClient: http://localhost:7501
    ports:
      - "7801:80"
    container_name: eventshubtokenapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokensqlserver

  cart:
    image: events/cartapi
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    environment:
      IdentityUrl: http://192.168.1.47:7801
      ConnectionString: basket.data
    ports:
      - "7012:80"
    container_name: eventscartapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokenserver
      - basket.data

  tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi123(!)
      SA_PASSWORD: ProductApi123(!)
    ports:
      - "1447:1433"
    container_name: eventshubtokensqlserver
    networks:
      - backend

  webmvc:
    image: eventshub/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://eventshubcatalogapi
      IdentityUrl: http://192.168.1.47:7801
      CallbackUrl: http://localhost:7501      
      CartUrl: http://cart
    ports:
      - "7501:80"
    container_name: eventswebshop
    networks:
      - frontend
    depends_on:
      - eventshubcatalogapi
      - tokenserver

  basket.data:
    image: redis
    ports:
      - "7060:6379"
    container_name: basketdata
    networks:
      - backend