version: '3.4'

networks:
  frontend:
  backend:

services:
  eventshubcatalogapi:
    image: eventshub/catalogapi
    build:
      context: .\EventsHubCatalogAPI
      dockerfile: Dockerfile
    environment:
       ConnectionString: "Data Source=mssqlserver;Initial Catalog=EventsHubDb;User Id=sa;Password=EventHubApi(!);TrustServerCertificate=false;Connect Timeout=30;Encrypt=false;"
       ExternalBaseUrl: https://localhost:7070
    ports:
         - "7070:80"
    container_name: eventshubcatalogapi
    networks: 
       - frontend
       - backend
    depends_on:
       -  mssqlserver
       
  tokenserver:
    image: eventshub/tokenapi
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=tokensqlserver;Initial Catalog=TokenServiceDb;User Id=sa;Password= EventHubApi(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      MvcClient: http://localhost:7075
    ports:
      - "7071:80"
    container_name: eventshubtokenapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokensqlserver


  webmvc:
    image: eventshub/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development44
      CatalogUrl: http://eventshubcatalogapi
      IdentityUrl: http://172.27.208.1:7071
      CallbackUrl: http://localhost:7075
    ports:
      - "7075:80"
    container_name: eventsshop
    networks:
      - frontend
    depends_on:
      - eventshubcatalogapi
      - tokenserver
   


  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
       ACCEPT_EULA: Y
       MSSAL_SA_PASSWORD: EventHubApi(!)
       SA_PASSWORD: EventHubApi(!)
    ports:
      - "1500:1433"
    container_name: eventhubsqlserver
    networks:
      - backend


  tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
       ACCEPT_EULA: Y
       MSSAL_SA_PASSWORD: EventHubApi(!)
       SA_PASSWORD: EventHubApi(!)
    ports:
      - "1501:1433"
    container_name: eventhubtokensqlserver
    networks:
      - backend




